skip_branch_with_pr: true

environment:
  APPVEYOR_RDP_PASSWORD: md847f75X0_1

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - choco install -y InnoSetup
  - git submodule update --init --recursive

build_script:
  - build.cmd

artifacts:
  - path: setup.exe
    name: Very Sleepy installer
  - path: symbols.7z
    name: Debugging symbols

test_script:
  - tests\tests\run_tests.bat

on_finish:
  - ps: $blockRdp = $true
